model:
  target: spamo.t5_slt.FlanT5SLT
  
  params:     
    lr: 6.0e-4
    monitor: val/bleu4
    model_name: google/flan-t5-xl
    cache_dir: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/SpaMo-BdSL/hf_cache
    inter_hidden: 768
    input_size: 2048
    beam_size: 5
    max_frame_len: 128
    max_txt_len: 64
    frame_sample_rate: 1
    prompt: "Translate the given sentence into {}."
    tuning_type: lora
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.1
    fusion_mode: joint
    warm_up_steps: 0
    cross_modal_align: true
    combined_loss: true
    alpha: 1.0
    use_in_context: true
    num_in_context: 3

lightning:
  callback:
    learning_rate_logger:
      target: pytorch_lightning.callbacks.LearningRateMonitor
      params:
        logging_interval: step
  trainer:
    accumulate_grad_batches: 8
    accelerator: gpu
    devices: 1
    max_epochs: 500
    gradient_clip_val: 1.0
    check_val_every_n_epoch: 2
    precision: bf16

data:
  target: dataset.datamodule.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 4
  
    train:
      target: dataset.p14t.Phoenix14T
      params:
        anno_root: ./preprocess/Phoenix14T
        vid_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/PHOENIX-2014-T-release-v3/PHOENIX-2014-T
        feat_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/spatial
        mae_feat_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/motion
        mode: train
        spatial: true
        spatiotemporal: true
        spatial_postfix: _s2wrapping
        spatiotemporal_postfix: _overlap-8-pretrained
        
    validation:
      target: dataset.p14t.Phoenix14T
      params:
        anno_root: ./preprocess/Phoenix14T
        vid_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/PHOENIX-2014-T-release-v3/PHOENIX-2014-T
        feat_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/spatial
        mae_feat_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/motion
        mode: test
        spatial: true
        spatiotemporal: true
        spatial_postfix: _s2wrapping
        spatiotemporal_postfix: _overlap-8-pretrained
    
    test:
      target: dataset.p14t.Phoenix14T
      params:
        anno_root: ./preprocess/Phoenix14T
        vid_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/PHOENIX-2014-T-release-v3/PHOENIX-2014-T
        feat_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/spatial
        mae_feat_root: /media/srbd4090b/61fed03e-e625-4aad-ae6c-b9c45cd1bb46/kowshik/motion
        mode: test
        spatial: true
        spatiotemporal: true
        spatial_postfix: _s2wrapping
        spatiotemporal_postfix: _overlap-8-pretrained
